### ISSUE TITLE
Alerts broken in Mojave

### ISSUE THREAD

**Issue by sasbury** [caseymrm/menuet#10]
The alert code needs to all happen in the main thread. I did a fix, but my github skills failed me when i tried to make a pull request. The fix is at https://github.com/sasbury/menuet/commit/fcad35b33689f3997c1a2c89d96a846e2dcbb60a

Basically move everything but the JSON dictionary into the async call in alert.m.

Sorry for the PR fail on my part.

**Comment by caseymrm** [comment]
Thanks for the contribution @sasbury , merged in https://github.com/caseymrm/menuet/commit/f94bbf2f498290cd4883cea92416e35215d5655e

I've given you write access if you'd like to make any other contributions directly. I'm really excited somebody else is finding this useful, let me know how I can help!
