### ISSUE TITLE
Why do you need that "Start at Login" Button?

### ISSUE THREAD

**Issue by meinto** [caseymrm/menuet#14]
<img width="115" alt="grafik" src="https://user-images.githubusercontent.com/2804678/75553604-03b43980-5a39-11ea-91d1-1eea11e940dd.png">

In my opinion it would be nice if the "Start at Login" button and the "Quit" button won't be there by default.

**Comment by hugows** [comment]
Some users like their apps autostarting and others don't ....

**Comment by caseymrm** [comment]
Thanks, this is good feedback- next time I'm in the code I'll add an option to suppress those if desired. They're primarily there because all of my apps wanted both.

**Comment by forfuncsake** [comment]
Fixed by #20?
