### ISSUE TITLE
GitHub Actions builds

### ISSUE THREAD

**Issue by mrusme** [caseymrm/menuet#19]
Hey there,

Thank you for this cool project, it made life a lot easier!

However, have you ever tried to successfully build a project that uses menuet on GitHub's CI? I have tried and failed using GoReleaser [on ubuntu-latest](https://github.com/mrusme/cloudcash/runs/8149166673?check_suite_focus=true#step:5:98), on [macos-latest](https://github.com/mrusme/cloudcash/runs/8149530737?check_suite_focus=true#step:5:87), and [a manual build](https://github.com/mrusme/cloudcash/runs/8158162651?check_suite_focus=true#step:5:57) on macos-latest. The jobs fail with the same error every time:

```
 # github.com/caseymrm/menuet
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/menuitem.go:47:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/menuitem.go:87:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/startup.go:12:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/startup.go:24:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/startup.go:36:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/startup.go:46:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/update.go:27:10: undefined: Application
Error: ../../../go/pkg/mod/github.com/caseymrm/menuet@v1.0.1/update.go:35:21: undefined: Alert

Error: The process '/Users/runner/hostedtoolcache/goreleaser-action/1.11.2/x64/goreleaser' failed with exit code 1
```

I successfully built the same code on a MacBook running the latest macOS and had no issue (apart from the few warnings in regard of macOS API deprecation).

Do you have an idea why these builds on GitHub fail?

Thank you!

**Comment by caseymrm** [comment]
Oooh, interesting- no, I haven't tried setting that up, sorry.
